spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/board}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    io.bootify.trollys: DEBUG